Repository dhall-lang/dhall-haskell, pull requests merged in 2020-07, with the labels that each got.

#1898 feat(dhall-docs): add type of expression from source code
  dhall-docs/dhall-docs.cabal
  dhall-docs/src/Dhall/Docs/Core.hs
  dhall-docs/src/Dhall/Docs/Html.hs
  dhall-docs/src/Dhall/data/Lato-Regular.ttf
  dhall-docs/src/Dhall/data/RobotoMono-Regular.ttf
  dhall-docs/src/Dhall/data/index.css
Labels: dhall-docs

#1899 feat(dhall-docs): Add test-setup and assertions as examples
  dhall-docs/dhall-docs.cabal
  dhall-docs/src/Dhall/Docs/Core.hs
  dhall-docs/src/Dhall/Docs/Html.hs
  dhall-docs/src/Dhall/Docs/Markdown.hs
  dhall-docs/src/Dhall/data/index.css
  dhall-docs/tasty/Main.hs
  dhall-docs/tasty/data/golden/IndexesExample.dhall.html
  dhall-docs/tasty/data/golden/InvalidMarkdown.dhall.html
  dhall-docs/tasty/data/golden/MarkdownExample.dhall.html
  dhall-docs/tasty/data/golden/Pair.dhall.html
  dhall-docs/tasty/data/golden/a/b.dhall.html
  dhall-docs/tasty/data/golden/a/b/c.dhall.html
  dhall-docs/tasty/data/golden/a/b/c/a.dhall.html
  dhall-docs/tasty/data/golden/a/b/c/index.html
  dhall-docs/tasty/data/golden/a/b/index.html
  dhall-docs/tasty/data/golden/a/index.html
  dhall-docs/tasty/data/golden/deep/nested/folder/index.html
  dhall-docs/tasty/data/golden/deep/nested/folder/my-even.dhall.html
  dhall-docs/tasty/data/golden/index.html
  dhall-docs/tasty/data/golden/package.dhall.html
  dhall-docs/tasty/data/package/IndexesExample.dhall
  dhall-docs/tasty/data/package/InvalidMarkdown.dhall
  dhall-docs/tasty/data/package/MarkdownExample.dhall
  dhall-docs/tasty/data/package/Pair.dhall
  dhall-docs/tasty/data/package/ShouldBeIgnored.dhall
  dhall-docs/tasty/data/package/a/b.dhall
  dhall-docs/tasty/data/package/a/b/c.dhall
  dhall-docs/tasty/data/package/a/b/c/a.dhall
  dhall-docs/tasty/data/package/deep/nested/folder/my-even.dhall
  dhall-docs/tasty/data/package/package.dhall
  nix/packages/HaXml.nix
  nix/packages/polyparse.nix
  nix/packages/tasty-silver.nix
  nix/sdist.nix
  stack.yaml
Labels: dhall-docs, merge me

#1901 First release of dhall-docs
  .travis.yml
  appveyor.yml
  scripts/release.sh
Labels: dhall-docs, merge me

#1912 feat(documentation): improve dhall-docs README.md with actual tool state
  dhall-docs/README.md
  dhall-docs/dhall-docs.cabal
Labels: dhall-docs, docs, merge me

#1913 dhall-lsp-server.cabal: Register test dependency on executable
  dhall-lsp-server/dhall-lsp-server.cabal
Labels: merge me

#1910 dhall-docs: filter non dhall file in generateDocs
  dhall-docs/dhall-docs.cabal
  dhall-docs/src/Dhall/Docs/Core.hs
  dhall-docs/tasty/Main.hs
  dhall-docs/tasty/data/package/InvalidUnicode.dhall
  dhall-docs/tasty/data/package/ShouldBeIgnoredToo
Labels: dhall-docs, merge me

#1915 Load italic and bold Lato fonts
  dhall-docs/src/Dhall/Docs/Html.hs
  dhall-docs/tasty/data/golden/IndexesExample.dhall.html
  dhall-docs/tasty/data/golden/InvalidMarkdown.dhall.html
  dhall-docs/tasty/data/golden/MarkdownExample.dhall.html
  dhall-docs/tasty/data/golden/Pair.dhall.html
  dhall-docs/tasty/data/golden/a/b.dhall.html
  dhall-docs/tasty/data/golden/a/b/c.dhall.html
  dhall-docs/tasty/data/golden/a/b/c/a.dhall.html
  dhall-docs/tasty/data/golden/a/b/c/index.html
  dhall-docs/tasty/data/golden/a/b/index.html
  dhall-docs/tasty/data/golden/a/index.html
  dhall-docs/tasty/data/golden/deep/nested/folder/index.html
  dhall-docs/tasty/data/golden/deep/nested/folder/my-even.dhall.html
  dhall-docs/tasty/data/golden/index.html
  dhall-docs/tasty/data/golden/package.dhall.html
Labels: dhall-docs, merge me

#1916 Alphabetize exported packages in dhall-docs
  dhall-docs/src/Dhall/Docs/Core.hs
  dhall-docs/tasty/data/golden/index.html
Labels: dhall-docs, merge me

#1902 Add new `dhall rewrite-with-schemas` subcommand
  dhall/dhall.cabal
  dhall/src/Dhall/Main.hs
  dhall/src/Dhall/Map.hs
  dhall/src/Dhall/Schemas.hs
  dhall/tests/Dhall/Test/Main.hs
  dhall/tests/Dhall/Test/Schemas.hs
  dhall/tests/Dhall/Test/TypeInference.hs
  dhall/tests/schemas/multipleA.dhall
  dhall/tests/schemas/multipleB.dhall
  dhall/tests/schemas/multipleSchema.dhall
  dhall/tests/schemas/personA.dhall
  dhall/tests/schemas/personB.dhall
  dhall/tests/schemas/personSchema.dhall
Labels: merge me

#1919 Fix broken README link
  dhall-lsp-server/dhall-lsp-server.cabal
Labels: merge me

#1921 Move man/dhall.1 to data files
  dhall/dhall.cabal
Labels: merge me

#1920 dhall-docs: add ascii characterset support
  dhall-docs/dhall-docs.cabal
  dhall-docs/src/Dhall/Docs.hs
  dhall-docs/src/Dhall/Docs/Core.hs
  dhall-docs/src/Dhall/Docs/Html.hs
  dhall-docs/tasty/Main.hs
Labels: dhall-docs, merge me

#1908 feat(comments): support prefix comments on Record's key-value pairs.
  dhall-bash/src/Dhall/Bash.hs
  dhall-json/dhall-json.cabal
  dhall-json/src/Dhall/JSON.hs
  dhall-json/src/Dhall/JSONToDhall.hs
  dhall-lsp-server/src/Dhall/LSP/Backend/Completion.hs
  dhall-nix/src/Dhall/Nix.hs
  dhall/src/Dhall.hs
  dhall/src/Dhall/Binary.hs
  dhall/src/Dhall/Core.hs
  dhall/src/Dhall/Diff.hs
  dhall/src/Dhall/DirectoryTree.hs
  dhall/src/Dhall/Eval.hs
  dhall/src/Dhall/Import.hs
  dhall/src/Dhall/Lint.hs
  dhall/src/Dhall/Normalize.hs
  dhall/src/Dhall/Parser/Expression.hs
  dhall/src/Dhall/Pretty/Internal.hs
  dhall/src/Dhall/Repl.hs
  dhall/src/Dhall/Schemas.hs
  dhall/src/Dhall/Syntax.hs
  dhall/src/Dhall/TH.hs
  dhall/src/Dhall/Tags.hs
  dhall/src/Dhall/TypeCheck.hs
  dhall/tests/Dhall/Test/Dhall.hs
  dhall/tests/Dhall/Test/QuickCheck.hs
  dhall/tests/Dhall/Test/Regression.hs
Labels: merge me

#1928 Add `dhall-docs` support for non-`let` type annotations
  dhall-docs/src/Dhall/Docs/Core.hs
  dhall-docs/tasty/data/golden/OrdinaryAnnotation.dhall.html
  dhall-docs/tasty/data/golden/TwoAnnotations.dhall.html
  dhall-docs/tasty/data/golden/index.html
  dhall-docs/tasty/data/package/OrdinaryAnnotation.dhall
  dhall-docs/tasty/data/package/TwoAnnotations.dhall
Labels: dhall-docs, dhall-docs:type-on-index, merge me

#1933 Fix `Arbitrary` instance for `File`/`Directory`
  dhall/tests/Dhall/Test/QuickCheck.hs
Labels: merge me

#1931 Fix `Arbitrary` instance for `URL`
  dhall/tests/Dhall/Test/QuickCheck.hs
Labels: merge me

#1930 Disable coverage-checking for shell
  dhall-docs/shell.nix
Labels: merge me

#1932 Fix `Arbitrary` instance for `Expr`
  dhall/tests/Dhall/Test/QuickCheck.hs
Labels: merge me

#1936 Fix `Arbitrary` instance for `Header`
  dhall/tests/Dhall/Test/QuickCheck.hs
Labels: merge me

#1937 Fix `Arbitrary` instances for `File`s (Take 2)
  dhall/tests/Dhall/Test/QuickCheck.hs
Labels: merge me

#1940 Shrink `Header`s to the empty string
  dhall/tests/Dhall/Test/QuickCheck.hs
Labels: merge me

#1943 Allow data-fix 0.3
  dhall-nix/dhall-nix.cabal
  dhall/dhall.cabal
  dhall/src/Dhall.hs
Labels: merge me

#1944 Allow tasty-expected-failure 0.12
  dhall-yaml/dhall-yaml.cabal
  dhall/dhall.cabal
Labels: merge me

#1945 feat(parsing): centralize comments parsing extraction on Dhall.Parser.Token
  dhall-docs/src/Dhall/Docs/Comment.hs
  dhall/dhall.cabal
  dhall/src/Dhall/Parser/Token.hs
Labels: merge me

#1948 Add trailing character to Text bullet point
  dhall-json/src/Dhall/JSON.hs
Labels: merge me

#1942 Fix `Arbitrary` instance for `Var`
  dhall/tests/Dhall/Test/QuickCheck.hs
Labels: merge me

#1953 Fix `subDelims` predicate for URL parsing
  dhall/src/Dhall/Parser/Token.hs
Labels: merge me

#1956 Mention Language Tour in `Dhall.Tutorial` module
  dhall/src/Dhall/Tutorial.hs
Labels: merge me

#1955 Remove expected failure for ListLitEmptyPrecedence test
  dhall/tests/Dhall/Test/Parser.hs
Labels: merge me

#1954 Fix parsing of annotated `toMap` and `merge` expressions
  dhall/src/Dhall/Parser/Expression.hs
  dhall/tests/Dhall/Test/Parser.hs
  dhall/tests/Dhall/Test/TypeInference.hs
Labels: merge me

#1958 Bring annotation parsing closer in line with the official grammar
  dhall/src/Dhall/Parser/Expression.hs
Labels: merge me

#1957 Handle empty lists without annotations as parse errors
  dhall/src/Dhall/Parser/Expression.hs
  dhall/src/Dhall/Tutorial.hs
  dhall/tests/Dhall/Test/Parser.hs
  dhall/tests/format/issue1400-1A.dhall
  dhall/tests/format/issue1400-1B.dhall
Labels: merge me

#1951 Test formatting idempotence with comments in let-bindings
  dhall/tests/Dhall/Test/QuickCheck.hs
Labels: merge me

#1961 Allow prettyprinter-1.7
  dhall-docs/dhall-docs.cabal
  dhall-json/dhall-json.cabal
  dhall-lsp-server/dhall-lsp-server.cabal
  dhall-nixpkgs/dhall-nixpkgs.cabal
  dhall-openapi/dhall-openapi.cabal
  dhall/dhall.cabal
Labels: merge me

#1962 Use path-0.8
  dhall-docs/dhall-docs.cabal
  nix/packages/path-io.nix
  nix/packages/path.nix
  stack.yaml
Labels: merge me

#1963 Correct a typo in tests/Dhall/Test/Dhall.hs
  dhall/tests/Dhall/Test/Dhall.hs
Labels: merge me
