Repository dhall-lang/dhall-haskell, pull requests merged in 2020-06, with the labels that each got.

#1833 feat(dhocs): add dhocs tool skeleton
  .gitignore
  cabal.project
  default.nix
  dhall-docs/CHANGELOG.md
  dhall-docs/LICENSE
  dhall-docs/README.md
  dhall-docs/Setup.hs
  dhall-docs/dhall-docs.cabal
  dhall-docs/dhall-docs/Main.hs
  dhall-docs/shell.nix
  dhall-docs/src/Dhall/Docs.hs
  dhall/src/Dhall/DirectoryTree.hs
  nix/shared.nix
  release.nix
  scripts/release.sh
  stack.yaml
Labels: merge me

#1829 Fix `zsh` completion support
  shell.nix
Labels: merge me

#1841 Build against `hnix-0.8`
  dhall-nix/dhall-nix.cabal
Labels: merge me

#1840 Add `--generated-comment` flag for `dhall-to-yaml{,-ng}`
  dhall-json/src/Dhall/DhallToYaml/Main.hs
  dhall-json/src/Dhall/JSON/Yaml.hs
  dhall-yaml/src/Dhall/Yaml.hs
Labels: merge me

#1842 Build against `doctest-0.17`
  dhall-lsp-server/dhall-lsp-server.cabal
  dhall/dhall.cabal
Labels: merge me

#1843 feat(debug): add --noted flag on haskell-syntax-tree
  dhall-docs/src/Dhall/Docs.hs
  dhall/src/Dhall/Main.hs
Labels: merge me

#1845 feat(dhall-docs): multi-page docs generation
  .gitignore
  .stylish-haskell.yaml
  dhall-docs/README.md
  dhall-docs/default.nix
  dhall-docs/dhall-docs.cabal
  dhall-docs/src/Dhall/Docs.hs
  dhall-docs/src/Dhall/Docs/Embedded.hs
  dhall-docs/src/Dhall/Docs/Html.hs
  dhall-docs/src/Dhall/data/Lato-Regular.ttf
  dhall-docs/src/Dhall/data/RobotoMono-Regular.ttf
  dhall-docs/src/Dhall/data/index.css
  nix/packages/lucid.nix
  stack.yaml
Labels: dhall-docs

#1844 Bump test dependencies for `dhall-lsp-server`
  nix/packages/QuickCheck.nix
  nix/packages/hnix.nix
  nix/packages/hspec-core.nix
  nix/packages/hspec-discover.nix
  nix/packages/hspec.nix
  nix/packages/parser-combinators.nix
  nix/packages/quickcheck-instances.nix
  nix/packages/semialign-indexed.nix
  nix/packages/semialign.nix
  nix/packages/some.nix
  nix/packages/splitmix.nix
  nix/packages/tasty-hspec.nix
  nix/packages/these.nix
  nix/packages/transformers-compat.nix
  nix/shared.nix
Labels: merge me

#1849 Fix double-nesting of `Note` constructors
  dhall/src/Dhall/Parser/Expression.hs
  dhall/tests/Dhall/Test/QuickCheck.hs
  dhall/tests/Dhall/Test/TypeInference.hs
Labels: merge me

#1852 release.sh: Include haddocks upload for dhall-nix
  scripts/release.sh
Labels: merge me

#1854 Narrow source span for unused let warnings
  dhall-lsp-server/src/Dhall/LSP/Backend/Linting.hs
  dhall-lsp-server/tests/Main.hs
Labels: merge me

#1858 Allow optparse-generic 1.4
  dhall-bash/dhall-bash.cabal
  dhall-nix/dhall-nix.cabal
Labels: merge me

#1848 feat(dhall-docs): improve ui/ux of generated documentation
  dhall-docs/README.md
  dhall-docs/dhall-docs.cabal
  dhall-docs/doctest/Main.hs
  dhall-docs/src/Dhall/Docs.hs
  dhall-docs/src/Dhall/Docs/Html.hs
  dhall-docs/src/Dhall/data/dhall-icon.svg
  dhall-docs/src/Dhall/data/index.css
  dhall-docs/src/Dhall/data/index.js
  dhall-lsp-server/dhall-lsp-server.cabal
  dhall/dhall.cabal
  nix/packages/path-io.nix
  nix/packages/path.nix
  release.nix
  scripts/release.sh
  stack.yaml
Labels: merge me

#1857 CBOR decoder performance
  dhall/src/Dhall/Binary.hs
Labels: merge me

#1861 Add GHCJS build target
  default.nix
Labels: merge me

#1851 Add textual information for Record and Union diff
  dhall/src/Dhall/Deriving.hs
  dhall/src/Dhall/Diff.hs
Labels: merge me

#1863 feat(dhall-docs): parse markdown from header
  dhall-docs/dhall-docs.cabal
  dhall-docs/src/Dhall/Docs.hs
  dhall-docs/src/Dhall/Docs/Html.hs
  dhall-docs/src/Dhall/Docs/Markdown.hs
  dhall-docs/src/Dhall/data/index.css
  dhall-docs/src/Dhall/data/index.js
  nix/packages/email-validate.nix
  nix/packages/microlens-th.nix
  nix/packages/mmark.nix
  nix/packages/modern-uri.nix
  nix/packages/text-metrics.nix
  nix/packages/unliftio-core.nix
  nix/packages/vector-algorithms.nix
Labels: dhall-docs, merge me

#1869 Update release script
  scripts/release.sh
Labels: merge me

#1867 Multi-line REPL
  dhall-nixpkgs/dhall-nixpkgs.cabal
  dhall/dhall.cabal
  dhall/src/Dhall/Repl.hs
  nix/packages/haskeline.nix
  nix/packages/haskeline_0_7_3_1.nix
  nix/packages/hnix.nix
  nix/packages/repline.nix
  stack.yaml
Labels: enhancement

#1871 feat(dhall-docs): add some dhall packages documentation to hydra pipelines
  dhall-docs/dhall-docs.cabal
  dhall-docs/src/Dhall/Docs.hs
  nix/dhall-docs-gen.nix
  nix/shared.nix
  release.nix
Labels: CI, build, dhall-docs, merge me

#1874 Document the difference between `dhall-to-yaml{,-ng}`
  dhall-yaml/README.md
Labels: merge me

#1644 Add cpkg benchmark
  dhall/benchmark/examples/cpkg.dhall
  dhall/benchmark/parser/Main.hs
Labels: merge me

#1877 Use env where it works
  dhall/benchmark/deep-nested-large-record/Main.hs
  dhall/benchmark/parser/Main.hs
Labels: merge me

#1881 Move RecordEncoder documentation
  dhall/src/Dhall.hs
Labels: merge me

#1876 feat(dhall-docs): Add content-addressed storage for documentation
  dhall-docs/README.md
  dhall-docs/dhall-docs.cabal
  dhall-docs/src/Dhall/Docs.hs
  dhall-docs/src/Dhall/Docs/Core.hs
  dhall-docs/src/Dhall/Docs/Store.hs
  nix/dhall-docs-gen.nix
Labels: dhall-docs, merge me

#1865 Format documents with leading `---`
  dhall-json/dhall-json.cabal
  dhall-json/src/Dhall/JSON/Yaml.hs
  dhall-yaml/src/Dhall/Yaml.hs
  dhall-yaml/tasty/Main.hs
  dhall-yaml/tasty/data/single-document-bare.dhall
  dhall-yaml/tasty/data/single-document-bare.yaml
  dhall-yaml/tasty/data/single-document.dhall
  dhall-yaml/tasty/data/single-document.yaml
  nix/packages/aeson-yaml.nix
  stack.yaml
Labels: merge me

#1879 Accelerate performance of trivial re-exports
  dhall/src/Dhall/Import.hs
  dhall/tests/Dhall/Test/TypeInference.hs
Labels: merge me

#1886 Disable optimizations for Dhall.Test.QuickCheck
  dhall/tests/Dhall/Test/QuickCheck.hs
Labels: merge me

#1880 Add `--transitive` flag to `dhall {format,lint,freeze}`
  dhall/dhall.cabal
  dhall/src/Dhall/Format.hs
  dhall/src/Dhall/Freeze.hs
  dhall/src/Dhall/Import.hs
  dhall/src/Dhall/Main.hs
  dhall/src/Dhall/Util.hs
Labels: merge me

#1892 feat(rendered-source): First iteration on rendered source code in the dhall documentation
  .gitignore
  dhall-docs/README.md
  dhall-docs/dhall-docs.cabal
  dhall-docs/src/Dhall/Docs/Core.hs
  dhall-docs/src/Dhall/Docs/Html.hs
  dhall-docs/src/Dhall/data/index.css
  nix/dhall-docs-gen.nix
Labels: dhall-docs, merge me

#1895 feat(dhall-docs): add breadcrumbs to improve navigation
  dhall-docs/src/Dhall/Docs.hs
  dhall-docs/src/Dhall/Docs/Core.hs
  dhall-docs/src/Dhall/Docs/Html.hs
  dhall-docs/src/Dhall/data/index.css
  dhall-docs/src/Dhall/data/index.js
Labels: dhall-docs

#1897 Fix #1884
  dhall/src/Dhall/Parser/Combinators.hs
  dhall/src/Dhall/Parser/Expression.hs
  dhall/tests/Dhall/Test/Regression.hs
  dhall/tests/regression/issue1884.dhall
Labels: merge me
